{"asctime": "2025-02-17 14:20:58,062", "msecs": 62.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:20:58,131", "msecs": 131.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:22:26,774", "msecs": 774.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:22:26,788", "msecs": 788.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:22:30,284", "msecs": 284.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:22:30,304", "msecs": 304.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:22:40,599", "msecs": 599.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:22:40,612", "msecs": 612.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:23:02,831", "msecs": 831.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:23:02,840", "msecs": 840.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:23:16,464", "msecs": 464.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:23:16,475", "msecs": 475.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:23:30,409", "msecs": 409.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:23:30,493", "msecs": 493.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:23:37,405", "msecs": 405.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:23:37,416", "msecs": 416.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:25:46,271", "msecs": 271.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:25:46,281", "msecs": 281.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:25:49,713", "msecs": 713.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:25:49,724", "msecs": 724.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:25:59,002", "msecs": 2.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:25:59,013", "msecs": 13.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:26:06,397", "msecs": 397.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:26:06,409", "msecs": 409.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:27:02,997", "msecs": 997.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:27:03,011", "msecs": 11.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:29:33,225", "msecs": 225.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:29:33,235", "msecs": 235.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:30:05,406", "msecs": 406.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:30:05,430", "msecs": 430.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:30:08,851", "msecs": 851.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:30:08,862", "msecs": 862.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:30:13,018", "msecs": 18.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:30:13,027", "msecs": 27.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:30:17,259", "msecs": 259.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:30:17,269", "msecs": 269.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:30:20,483", "msecs": 483.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:30:20,496", "msecs": 496.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:30:23,714", "msecs": 714.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:30:23,725", "msecs": 725.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:34:48,880", "msecs": 880.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:34:48,891", "msecs": 891.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:39:09,402", "msecs": 402.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:39:09,416", "msecs": 416.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:46:13,661", "msecs": 661.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:46:13,707", "msecs": 707.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:48:51,793", "msecs": 793.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:48:51,804", "msecs": 804.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:48:55,309", "msecs": 309.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:48:55,338", "msecs": 338.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:49:51,070", "msecs": 70.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 23, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:49:51,094", "msecs": 94.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:49:54,944", "msecs": 944.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:49:54,960", "msecs": 960.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:50:21,681", "msecs": 681.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:50:21,693", "msecs": 693.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:55:34,265", "msecs": 265.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:55:34,282", "msecs": 282.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:55:34,458", "msecs": 458.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:55:34,474", "msecs": 474.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:55:39,142", "msecs": 142.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:55:39,158", "msecs": 158.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:55:39,193", "msecs": 193.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:55:39,202", "msecs": 202.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:55:43,793", "msecs": 793.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:55:43,810", "msecs": 810.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:55:43,863", "msecs": 863.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:55:43,878", "msecs": 878.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:03,354", "msecs": 354.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:03,373", "msecs": 373.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:03,597", "msecs": 597.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:04,522", "msecs": 522.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:09,333", "msecs": 333.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:09,345", "msecs": 345.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:10,111", "msecs": 111.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:10,127", "msecs": 127.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:15,043", "msecs": 43.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:15,064", "msecs": 64.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:15,605", "msecs": 605.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:15,622", "msecs": 622.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:20,334", "msecs": 334.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:20,346", "msecs": 346.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:20,542", "msecs": 542.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:20,558", "msecs": 558.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:25,009", "msecs": 9.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:25,023", "msecs": 23.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:25,202", "msecs": 202.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:25,227", "msecs": 227.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:29,972", "msecs": 972.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:29,989", "msecs": 989.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:56:30,047", "msecs": 47.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:56:30,063", "msecs": 63.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:10,082", "msecs": 82.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:10,101", "msecs": 101.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:10,231", "msecs": 231.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:10,245", "msecs": 245.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:15,236", "msecs": 236.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:15,307", "msecs": 307.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:15,434", "msecs": 434.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:15,444", "msecs": 444.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:19,721", "msecs": 721.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:19,771", "msecs": 771.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:20,206", "msecs": 206.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:20,230", "msecs": 230.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:27,105", "msecs": 105.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:27,121", "msecs": 121.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:27,125", "msecs": 125.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:27,137", "msecs": 137.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:31,848", "msecs": 848.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:31,865", "msecs": 865.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:31,858", "msecs": 858.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:31,878", "msecs": 878.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:37,612", "msecs": 612.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:37,628", "msecs": 628.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:57:37,683", "msecs": 683.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:57:37,695", "msecs": 695.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:58:25,193", "msecs": 193.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:58:25,210", "msecs": 210.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:58:25,362", "msecs": 362.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:58:25,380", "msecs": 380.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:58:30,842", "msecs": 842.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:58:30,859", "msecs": 859.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:58:31,064", "msecs": 64.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:58:31,077", "msecs": 77.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 14:58:35,095", "msecs": 95.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 693, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Osliani\\.pyenv\\pyenv-win\\versions\\3.12.8\\Lib\\contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Osliani\\Proyectos\\Jumo_FastApi\\chatbot\\api.py\", line 24, in lifespan\n    await database.connect()\n          ^^^^^^^^^^^^^^^^\nAttributeError: module 'chatbot.database' has no attribute 'connect'\n"}
{"asctime": "2025-02-17 14:58:35,111", "msecs": 111.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-02-17 15:03:22,782", "msecs": 782.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 62, "message": "Application startup complete."}
